"""
Test suite for the Accident Severity Classification API (v2 taxonomy).

Runs every case in tests/fixtures.json (generated by tests/make_fixtures.py):
  - GET /health matches the validated build (model, thresholds, taxonomy)
  - designed Normal / Moderate / Severe windows return their intended class
  - random real hold-out windows return exactly what the validated build returns
    (severity, label_source, signature_match, p_crash within 0.002); their TRUE
    label is reported alongside, so model errors remain visible
  - contract: missing field, wrong length, non-JSON, NaN, Infinity, null -> 400

Usage:
    python test_api.py                       # http://localhost:5000
    python test_api.py --url http://host:port
    python test_api.py --prod                # Railway production
Exit code 0 only if every check passes. Full log -> api_test_results[_prod].txt
"""
import argparse
import json
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path

HERE = Path(__file__).parent
PROD_URL = "https://accident-severity-api-production.up.railway.app"


def http(base, path, raw=None, content_type="application/json", timeout=60):
    req = urllib.request.Request(base + path, data=raw.encode() if raw is not None else None,
                                 headers={"Content-Type": content_type} if raw is not None else {},
                                 method="POST" if raw is not None else "GET")
    t0 = time.perf_counter()
    try:
        with urllib.request.urlopen(req, timeout=timeout) as r:
            return r.status, json.loads(r.read()), (time.perf_counter() - t0) * 1000
    except urllib.error.HTTPError as e:
        return e.code, json.loads(e.read()), (time.perf_counter() - t0) * 1000


def run(base):
    fx = json.load(open(HERE / "tests" / "fixtures.json"))
    lines, passed, failed = [], 0, 0

    def log(s=""):
        print(s); lines.append(s)

    def check(ok, msg):
        nonlocal passed, failed
        passed += ok; failed += (not ok)
        log(f"  [{'PASS' if ok else 'FAIL'}] {msg}")

    log("=" * 78)
    log("Accident Severity API - test results")
    log(f"Timestamp : {time.strftime('%Y-%m-%d %H:%M:%S')}")
    log(f"Target    : {base}")
    log(f"Fixtures  : {fx['generated_from']}")
    log("=" * 78)

    log("\n[HEALTH]")
    st, h, _ = http(base, "/health")
    log(f"  {json.dumps(h)}")
    check(st == 200 and h.get("status") == "healthy", "GET /health -> 200 healthy")
    for k, v in fx["health"].items():
        got = h.get(k)
        ok = abs(got - v) < 1e-6 if isinstance(v, float) and isinstance(got, (int, float)) else got == v
        check(ok, f"health.{k} == {v!r} (got {got!r})")

    log("\n[CLASSIFICATION]")
    agree = {"synthetic": [0, 0], "real": [0, 0]}
    per_class = {}
    for c in fx["cases"]:
        e = c["expected"]
        st, r, ms = http(base, "/predict", json.dumps(c["payload"]))
        if st != 200:
            check(False, f"{c['name']}: HTTP {st} {r}")
            continue
        log(f"  {c['name']}")
        log(f"    returned {r['severity_name']:8s} | true {c['true_label']:8s} | p_crash {r['p_crash']:.4f} | "
            f"label_source {r['label_source']} | sig {r['crash_signature']} | {ms:.0f} ms")
        check(r["severity_name"] == e["severity_name"], f"severity_name == {e['severity_name']}")
        check(r["label_source"] == e["label_source"], f"label_source == {e['label_source']}")
        check(r["crash_signature"]["signature_match"] == e["signature_match"], f"signature_match == {e['signature_match']}")
        check(abs(r["p_crash"] - e["p_crash"]) <= 0.002, f"p_crash {r['p_crash']} within 0.002 of {e['p_crash']}")
        check(r["accident_confirmed"] == (r["severity_class"] >= 1), "accident_confirmed consistent with severity_class")
        a = agree[c["kind"]]; a[1] += 1; a[0] += r["severity_name"] == c["true_label"]
        pc = per_class.setdefault(c["true_label"], [0, 0]); pc[1] += 1; pc[0] += r["severity_name"] == c["true_label"]
    returned = {c["expected"]["severity_name"] for c in fx["cases"]}
    check({"Normal", "Moderate", "Severe"} <= returned, "all three classes (Normal, Moderate, Severe) are produced")

    log("\n[CONTRACT]")
    for c in fx["contract"]:
        raw = c.get("raw", json.dumps(c.get("body")))
        st, r, _ = http(base, "/predict", raw, c.get("content_type", "application/json"))
        check(st == c["status"] and c["error_includes"] in r.get("error", ""),
              f"{c['name']} (got {st} {r.get('error')!r})")

    log("\n" + "=" * 78)
    log(f"Checks: {passed} passed, {failed} failed")
    log(f"True-label agreement - designed: {agree['synthetic'][0]}/{agree['synthetic'][1]}, "
        f"real hold-out: {agree['real'][0]}/{agree['real'][1]} "
        f"(per class: {', '.join(f'{k} {v[0]}/{v[1]}' for k, v in per_class.items())})")
    log("(real-window agreement is a small random sample; system accuracy is in phase5/PHASE5_REPORT.md)")
    log("=" * 78)
    out = HERE / ("api_test_results_prod.txt" if base == PROD_URL else "api_test_results.txt")
    out.write_text("\n".join(lines), encoding="utf-8")
    return failed == 0


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description="Accident Severity API test suite")
    ap.add_argument("--url", default="http://localhost:5000")
    ap.add_argument("--prod", action="store_true")
    a = ap.parse_args()
    sys.exit(0 if run(PROD_URL if a.prod else a.url.rstrip("/")) else 1)
