// AUTO-GENERATED by tools/gen_firmware_profiles.py from artifacts/threshold_profiles.json.
// Do not edit by hand: regenerate, and tests/test_profiles.py checks it is current.
#pragma once

struct ThresholdProfile {
  const char* name;              // profile whose thresholds are compiled in
  const char* requested;         // what the build flag asked for
  const char* note;              // why name differs from requested (nullptr if it does not)
  double peak_min_g;             // also the run level for the excursion and impulse
  double peak_max_g;
  double dur_min_ms;
  double dur_max_ms;
  double severe_impulse_gs;
  const char* severity_grading;  // server grading rule; classifyLocally() always grades by impulse
};

// Selection is compile-time. Default (no flag) is production.
//   #define THRESHOLD_PROFILE_DEMO_RC   before including this header -> demo_rc
#if defined(THRESHOLD_PROFILE_DEMO_RC)
#warning "THRESHOLD_PROFILE_DEMO_RC requested but demo_rc is pending_measurement (not derived from measured data); fell back to production"
static const ThresholdProfile ACTIVE_THRESHOLD_PROFILE = {"production", "demo_rc", "demo_rc is pending_measurement (not derived from measured data); fell back to production", 2.0, 7.0, 40.0, 250.0, 0.959, "model_ratio"};
#else
static const ThresholdProfile ACTIVE_THRESHOLD_PROFILE = {"production", "production", nullptr, 2.0, 7.0, 40.0, 250.0, 0.959, "model_ratio"};
#endif

// Server pre-filter: scipy.signal.butter(4, 20/(100/2), 'low', output='sos'), applied with
// sosfiltfilt (odd padding). Coefficients: b0 b1 b2 a0 a1 a2 per section.
static const int GATE_FS_HZ = 100;
static const int GATE_SOS_SECTIONS = 2;
static const int GATE_PADLEN = 15;
static const double GATE_SOS[GATE_SOS_SECTIONS][6] = {
  {0.046582906636443641, 0.093165813272887282, 0.046582906636443641, 1, -0.32897567737095307, 0.064587654916442999},
  {1, 2, 1, 1, -0.45311952065238476, 0.46632557076323672},
};
static const double GATE_ZI[GATE_SOS_SECTIONS][2] = {
  {0.20671860589126925, 0.030222755955490659},
  {0.74669848747228673, -0.21302405823552364},
};
