"""Compile artifacts/threshold_profiles.json into the firmware header.

The device and the server must apply the same gate, so the firmware never
hardcodes thresholds: this script writes
firmware/ESP32_Complete_3LED_System/threshold_profiles.h with both profiles and
the server's 20 Hz Butterworth coefficients (sos, sosfilt_zi, odd-padding length)
exactly as scipy.signal.sosfiltfilt uses them.
tests/test_profiles.py fails if the committed header drifts from the JSON.

Usage:  python tools/gen_firmware_profiles.py            # write header
        python tools/gen_firmware_profiles.py --check    # exit 1 if out of date
"""
import argparse
import json
import sys
from pathlib import Path

from scipy import signal

ROOT = Path(__file__).resolve().parents[1]
PROFILES = ROOT / "artifacts" / "threshold_profiles.json"
HEADER = ROOT / "firmware" / "ESP32_Complete_3LED_System" / "threshold_profiles.h"
KEYS = ("peak_min_g", "peak_max_g", "dur_min_ms", "dur_max_ms", "severe_impulse_gs")
FS, CUTOFF_HZ, ORDER = 100, 20.0, 4          # must match app.py (_SOS); asserted in tests


def filter_design():
    sos = signal.butter(ORDER, CUTOFF_HZ / (FS / 2.0), btype="low", output="sos")
    ntaps = 2 * len(sos) + 1 - min(int((sos[:, 2] == 0).sum()), int((sos[:, 5] == 0).sum()))
    return sos, signal.sosfilt_zi(sos), 3 * ntaps


def _f(v):
    return f"{float(v):.17g}"


def _profile_init(name, p, requested, note):
    vals = ", ".join(repr(float(p[k])) for k in KEYS)
    note_s = f'"{note}"' if note else "nullptr"
    return f'{{"{name}", "{requested}", {note_s}, {vals}, "{p["severity_grading"]}"}}'


def render():
    defs = json.loads(PROFILES.read_text(encoding="utf-8"))["profiles"]
    prod, demo = defs["production"], defs["demo_rc"]
    demo_ok = demo.get("status") == "derived" and all(isinstance(demo.get(k), (int, float)) for k in KEYS)
    sos, zi, padlen = filter_design()
    out = [
        "// AUTO-GENERATED by tools/gen_firmware_profiles.py from artifacts/threshold_profiles.json.",
        "// Do not edit by hand: regenerate, and tests/test_profiles.py checks it is current.",
        "#pragma once",
        "",
        "struct ThresholdProfile {",
        "  const char* name;              // profile whose thresholds are compiled in",
        "  const char* requested;         // what the build flag asked for",
        "  const char* note;              // why name differs from requested (nullptr if it does not)",
        "  double peak_min_g;             // also the run level for the excursion and impulse",
        "  double peak_max_g;",
        "  double dur_min_ms;",
        "  double dur_max_ms;",
        "  double severe_impulse_gs;",
        "  const char* severity_grading;  // server grading rule; classifyLocally() always grades by impulse",
        "};",
        "",
        "// Selection is compile-time. Default (no flag) is production.",
        "//   #define THRESHOLD_PROFILE_DEMO_RC   before including this header -> demo_rc",
        "#if defined(THRESHOLD_PROFILE_DEMO_RC)",
    ]
    if demo_ok:
        out.append(f"static const ThresholdProfile ACTIVE_THRESHOLD_PROFILE = {_profile_init('demo_rc', demo, 'demo_rc', None)};")
    else:
        note = f"demo_rc is {demo.get('status')} (not derived from measured data); fell back to production"
        out += [f'#warning "THRESHOLD_PROFILE_DEMO_RC requested but {note}"',
                f"static const ThresholdProfile ACTIVE_THRESHOLD_PROFILE = {_profile_init('production', prod, 'demo_rc', note)};"]
    out += [
        "#else",
        f"static const ThresholdProfile ACTIVE_THRESHOLD_PROFILE = {_profile_init('production', prod, 'production', None)};",
        "#endif",
        "",
        f"// Server pre-filter: scipy.signal.butter({ORDER}, {CUTOFF_HZ:g}/({FS}/2), 'low', output='sos'), applied with",
        "// sosfiltfilt (odd padding). Coefficients: b0 b1 b2 a0 a1 a2 per section.",
        f"static const int GATE_FS_HZ = {FS};",
        f"static const int GATE_SOS_SECTIONS = {len(sos)};",
        f"static const int GATE_PADLEN = {padlen};",
        "static const double GATE_SOS[GATE_SOS_SECTIONS][6] = {",
        *[f"  {{{', '.join(_f(v) for v in row)}}}," for row in sos],
        "};",
        "static const double GATE_ZI[GATE_SOS_SECTIONS][2] = {",
        *[f"  {{{', '.join(_f(v) for v in row)}}}," for row in zi],
        "};",
        "",
    ]
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    text = render()
    if a.check:
        current = HEADER.read_text(encoding="utf-8") if HEADER.exists() else ""
        if current != text:
            print(f"{HEADER} is out of date; run python tools/gen_firmware_profiles.py")
            sys.exit(1)
        print("firmware header is current")
        return
    HEADER.parent.mkdir(parents=True, exist_ok=True)
    HEADER.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {HEADER}")


if __name__ == "__main__":
    main()
